"""
WhatsApp Notifier Service
Integrates local Node.js WhatsApp Web microservice to send live WhatsApp job alerts.
"""
import httpx
import sys
import random

# Force UTF-8 output on Windows to prevent UnicodeEncodeErrors in console prints
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

WHATSAPP_SERVICE_URL = "http://localhost:8005"

def get_whatsapp_signature() -> str:
    """Return a dynamic, capitalized, emoji-rich signature for WhatsApp notifications."""
    templates = [
        "🚀 SENT BY DIWAKAR PRATAP",
        "✨ POWERED BY DIWAKAR PRATAP",
        "🔥 DISCOVERED BY DIWAKAR PRATAP",
        "🎯 CURATED BY DIWAKAR PRATAP",
        "🤖 AUTOMATED BY DIWAKAR PRATAP",
        "⚡ GENERATED BY DIWAKAR PRATAP",
        "🌟 DELIVERED BY DIWAKAR PRATAP",
        "💡 SOURCE: DIWAKAR PRATAP",
        "👑 BROUGHT TO YOU BY DIWAKAR PRATAP"
    ]
    return f"*_{random.choice(templates)}_*"

async def send_whatsapp_alert(phone: str, message: str) -> bool:
    """Send a WhatsApp message via the Node.js WhatsApp microservice."""
    print(f"[WhatsApp Notifier] Queueing message to {phone}: {message[:60]}...")
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{WHATSAPP_SERVICE_URL}/send",
                json={"phone": phone, "message": message},
                timeout=10.0
            )
            if response.status_code == 200:
                data = response.json()
                if data.get("success"):
                    print(f"[WhatsApp Notifier] Message sent successfully to {phone}")
                    return True
            print(f"[WhatsApp Notifier Warning] Failed to send message to {phone}. Status code: {response.status_code}, Response: {response.text}")
            return False
    except Exception as e:
        print(f"[WhatsApp Notifier Error] Failed to send message to {phone}: {e}")
        return False
